version: "3.7"
services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    command: nodemon server.js
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"

networks:
  default:
    name: user-login-boilerplate-network